feat: added dialog custom drink
corso-android-ivan-morgillo/team-b pull request #211
Opened 2021-03-29 13:35 UTC by Mirko494

2021-03-29 13:37 UTC, Santo-G approved these changes

2021-03-30 07:12 UTC, Domenico141 approved these changes

2021-03-30 14:04 UTC, LucreziaC commented
O.O!!! Mi hai tolto dai reviewes???? No ma me la segno

2021-03-31 08:13 UTC, Santo-G approved these changes

2021-03-31 10:39 UTC, Santo-G approved these changes

2021-03-31 10:40 UTC, LucreziaC requested changes
devi cambiare tutto. Entro ieri devi rifare tutto il progetto

2021-03-31 10:43 UTC, LucreziaC approved these changes

2021-03-31 10:43 UTC, merged